### ISSUE TITLE
Possible to apply className to <pre> element?

### ISSUE THREAD

**Issue by MichaelMarcialis** [conorhastings/react-syntax-highlighter#102]
Forgive me; I'm still a bit new to React. I've implemented your `react-syntax-highlighter`, but am currently unable to apply a custom class to the containing `<pre>` element being generated. Using the prop `className` on the component does nothing, and the README only indicates that the `<code>` elements class is alterable. Is there currently no way to apply a custom class to the `<pre>` element?

**Comment by conorhastings** [comment]
Yes, props that are not specfically mentioned will be spread through to the pre element (see this mentioned at end of prop section)

simple example here -- https://codesandbox.io/s/x2zyp7x43o
