### ISSUE TITLE
Issue with json/js in jsx

### ISSUE THREAD

**Issue by ivgrin** [conorhastings/react-syntax-highlighter#107]
I'm trying to render this code:

    <Table
        preset="example"
        data={[
            {
                id: 1,
                name: "Name1",
                new: false
            },
            {
                id: 2,
                name: "Name2",
                new: true
            }
        ]}
        rowClass={row => {
            if (row.new) {
                return "new";
            }
        }}
    />

It gives me the next result:

<img width="426" alt="screen shot 2018-03-05 at 13 34 53" src="https://user-images.githubusercontent.com/11681966/36970690-773c91c2-207a-11e8-8963-93415195c480.png">

It seems that it doesn't parse json objects/arrays inside jsx. As well as function's code.

Compare it with this code:

    <Table
        preset="example"
        data={data}
        rowClass={row => {

        }}
    />

<img width="372" alt="screen shot 2018-03-05 at 13 35 18" src="https://user-images.githubusercontent.com/11681966/36970785-c069bba4-207a-11e8-965f-9ad6bb332fd1.png">

**Comment by ivgrin** [comment]
package.json:

    "react-syntax-highlighter": "^7.0.1"

In use:

    'use strict';

    import React from 'react';
    import SyntaxHighlighter from 'react-syntax-highlighter/prism';
    import style from 'react-syntax-highlighter/styles/prism/pojoaque.js';

    export default class Example extends React.Component {

        render() {

            let customStyle = {
                ...style,
                'code[class*="language-"]': {
                    fontSize: '14px'
                },
                'pre[class*="language-"]': {
                    fontSize: '14px'
                },
                'attr-name': {
                    color: '#6596ae'
                },
                'attr-value': {
                    color: '#bbb',
                    fontStyle: 'italic',
                    letterSpacing: '0.5px'
                },
                'number': {
                    color: '#bbb',
                    fontStyle: 'italic',
                    letterSpacing: '0.5px'
                },
                'boolean': {
                    color: '#bbb',
                    fontStyle: 'italic',
                    letterSpacing: '0.5px'
                },
                'constant': {
                    color: '#bbb',
                    fontStyle: 'italic',
                    letterSpacing: '0.5px'
                },
                'symbol': {
                    color: '#bbb',
                    fontStyle: 'italic',
                    letterSpacing: '0.5px'
                },
                'property': {
                    color: '#bbb',
                    fontStyle: 'italic',
                    letterSpacing: '0.5px'
                },
                'punctuation': {
                    color: '#636a6c',
                },
                'tag': {
                    color: '#bea488'
                }
            };

            let code = `
                <Table
                    preset="example"
                    data={[
                        {
                            id: 1,
                            name: "Name1",
                            new: false
                        },
                        {
                            id: 2,
                            name: "Name2",
                            new: true
                        }
                    ]}
                    rowClass={row => {
                        if (row.new) {
                            return "new";
                        }
                    }}
                />
            `;

            return (
                <SyntaxHighlighter language="jsx" style={customStyle}>
                    {code}
                </SyntaxHighlighter>
            );
        }

    };

**Comment by conorhastings** [comment]
@ivgrin sorry for the late reply, currently in the processing of moving, thank you for the example, i will look as soon as i find the time

**Comment by conorhastings** [comment]
I'm not sure the expected result but from what you pasted, this looks fine to me?

https://codesandbox.io/s/2wxo057y0p

please reopen if i'm missing something
