### ISSUE TITLE
how to use it with Markdown parser

### ISSUE THREAD

**Issue by leoMeee** [conorhastings/react-syntax-highlighter#11]
i used  this  [Markdown parser](https://github.com/evilstreak/markdown-js)

`<SyntaxHighlighter language='javascript' style={docco} >`
              `{markdown.toHTML('##Use npm `npm init --yes`')}`
`</SyntaxHighlighter>`

then i got

`<h2>Use npm  <code>npm init --yes</code></h2> `

**Comment by conorhastings** [comment]
what are you expecting the output to be?

**Comment by leoMeee** [comment]
i want to get "Unescaped html".
 i dont know how to do with react-syntax-highlighter and Markdown parser

**Comment by conorhastings** [comment]
i'm not totally ure what markdown parser does, so i'm not sure i can be much help here
