### ISSUE TITLE
unusual color after comments in javascript mode

### ISSUE THREAD

**Issue by o02112** [conorhastings/react-syntax-highlighter#110]
unusual color show when a word after comments
![image](https://user-images.githubusercontent.com/4658927/37583187-45c519d6-2b8b-11e8-9bf0-f91f68ea064a.png)
![image](https://user-images.githubusercontent.com/4658927/37583209-63847ae8-2b8b-11e8-8960-7be43fe0cbd1.png)
![image](https://user-images.githubusercontent.com/4658927/37583296-d468791c-2b8b-11e8-97b7-4d2587a561a7.png)

**Comment by conorhastings** [comment]
i'll take a look as soon as i can but am currently moving so it may take a bit of time, if you could post the full code sample that would be super helpful.

**Comment by o02112** [comment]
```
 // package.json
"react-syntax-highlighter": "^5.8.0",
```

```
import SyntaxHighlighter from 'react-syntax-highlighter';


<SyntaxHighlighter language={language.code} style={atomOneLight} showLineNumbers>
    {`
APIGateway("${requestPath}", {
    version: "${this.state.version}",
    data: {
        // 接口参数
        "param1": "value1",
        "param2": "value2"
    }
}).then(response => {
    console.log(response);
}).catch(error => {
    console.log(error);
});`
}
</SyntaxHighlighter>

```

**Comment by conorhastings** [comment]
this appears to be an upstream issue with highlightjs -- https://codepen.io/conorhastings/pen/PRpKEG -- i would suggest filing a bug there
