### ISSUE TITLE
Got yarn errors after upgrading React version to 16.2.0

### ISSUE THREAD

**Issue by burrack** [conorhastings/react-syntax-highlighter#113]
Hi,

I got those error after upgrading react version from 15 to 16.2.0.
react-syntax-highlight#react@^15.3.0" doesn't satisfy found match of "react@16.2.0"
react-syntax-highlight#react-dom@^15.3.0" doesn't satisfy found match of "react-dom@16.2.0"

Thanks for the help!

**Comment by conorhastings** [comment]
@burrack react-syntax-highlight is a different library with a peerDependency that is causing your error -- https://github.com/zlargon/react-highlight/blob/master/package.json#L33

This library allows anything greater than react 14 https://github.com/conorhastings/react-syntax-highlighter/blob/master/package.json#L39
