### ISSUE TITLE
Missing types (typeScript errors)

### ISSUE THREAD

**Issue by whitneymarkov** [conorhastings/react-syntax-highlighter#118]
`[ts]
Could not find a declaration file for module 'react-syntax-highlighter/styles/prism'. 'PATH/node_modules/react-syntax-highlighter/styles/prism/index.js' implicitly has an 'any' type.
  Try 'npm install @types/react-syntax-highlighter' if it exists or add a new declaration (.d.ts) file containing "declare module 'react-syntax-highlighter"'`

This error applies to the following:
`import SyntaxHighlighter from 'react-syntax-highlighter/prism';`
`import { STYLE_NAME } from 'react-syntax-highlighter/styles/prism';`
`import { STYLE_NAME } from 'react-syntax-highlighter/styles/hljs';`

It does not apply to any imports directly from `'react-syntax-highlighter'`. I have not tried this with the light build.

**Comment by conorhastings** [comment]
This library has no support for typescript out of the box i believe definitely-typed has a type declaration so I would check there
