### ISSUE TITLE
some styles of Prism is missing

### ISSUE THREAD

**Issue by eldyvoon** [conorhastings/react-syntax-highlighter#119]
Is this list updated? https://github.com/conorhastings/react-syntax-highlighter/blob/master/AVAILABLE_STYLES_PRISM.MD

Some values are not valid coz it's missing, eg. atomDark, duotoneDark etc.

**Comment by LuisReinoso** [comment]
Hi!. In your source code have a lot styles for prims but on production only have this.
![imagen](https://user-images.githubusercontent.com/7484215/53690978-e758c080-3d42-11e9-808c-498763b9d741.png)

**Comment by conorhastings** [comment]
@LuisReinoso that looks like the tree for prism-react-renderer, a different package
