### ISSUE TITLE
Does not highlight a brace after a quote for a prop

### ISSUE THREAD

**Issue by dextermb** [conorhastings/react-syntax-highlighter#128]
Hey there! Awesome package. I noticed this in my discover weekly.

I ran a small test:
```
function render() {
  return <div key={"a"} />
}
```

Which output:
<img width="293" alt="screen shot 2018-08-02 at 13 11 00" src="https://user-images.githubusercontent.com/6137789/43582865-b0d3f348-9655-11e8-9f5d-e67b39806116.png">

As you can see the `}` after `"` (same with `'`) does not seem to be highlighted correctly.

Any ideas for a solution?

**Comment by conorhastings** [comment]
can you post full code sample including use of SyntaxHighlighter

**Comment by dextermb** [comment]
@conorhastings this was just on your demo page. Added the test code to the bottom of it

**Comment by conorhastings** [comment]
@dextermb react code will only render properly with prism, see -- http://conor.rodeo/react-syntax-highlighter/demo/prism
