### ISSUE TITLE
Massive filesize

### ISSUE THREAD

**Issue by gerardmrk** [conorhastings/react-syntax-highlighter#13]
This package just added 600kb to my production bundle. I actually really like this lib, but the filesize could be a dealbreaker for me. I tried not importing styles but filesize is still the same. Right now my only workaround is to include react-syntax-highlighter in my vendor bundle and exclude it from the main app bundle.

https://gyazo.com/c9bbe6b0f9fd5917c3abb020ce980c14

The only comfort I have from this is that it's down to 200+kb after gzipped.

**Comment by conorhastings** [comment]
yeah, I've been trying to think a lot about this problem. It's mostly due to the way we handle the lowlight import. It seems clunky to have the user register a language by reaching into the lowlight internals but that would massively cut filesize, perhaps we could offer a light build. would that interest you?

**Comment by goozo** [comment]
The package looks awesome and exactly what I'm looking for to use in production, but the filesize is a deal breaker, I would be fine with reaching into internals to register a language or a light build.

**Comment by conorhastings** [comment]
@goozo sounds good, I'll try to get it released this weekend.

**Comment by gerardmrk** [comment]
@conorhastings yes that would be nice thanks!

**Comment by conorhastings** [comment]
@gerardmrk @goozo sorry for the delay, busy with work. See this commit https://github.com/conorhastings/react-syntax-highlighter/commit/90607dbb023becb7a8d816f3e433366acef47e46 (published as `v2.2.0`) and see if that works for you! I tried it ad able to see a 10x drop in package size for something I am using this for!
