### ISSUE TITLE
Typescript + React support?

### ISSUE THREAD

**Issue by lioneltay** [conorhastings/react-syntax-highlighter#130]
I was just wondering if its possible to get syntax highlighting for typescript and react together? Like in .tsx files.

I notice you can get typescript highlighting without react and that javascript highlighting automatically includes react.

Really enjoying the component!

**Comment by conorhastings** [comment]
if you use the prism version

```js
import SyntaxHighlighter from 'react-syntax-highlighter/prism';
```
than tsx is a supported language.

Hope this helps! Thanks for using!
