### ISSUE TITLE
Line wrapping support

### ISSUE THREAD

**Issue by kbirger** [conorhastings/react-syntax-highlighter#134]
It would be nice to have line wrapping support here. I'm not sure if it's easily achievable by mixing and matching styles applied to lines.

**Comment by conorhastings** [comment]
I don't have the time to do this, but will leave open if someone else wants to tackle

**Comment by conorhastings** [comment]
goingt o close in favor of https://github.com/conorhastings/react-syntax-highlighter/issues/143
