### ISSUE TITLE
Disabling horizontal scrollbars

### ISSUE THREAD

**Issue by TheRav3n** [conorhastings/react-syntax-highlighter#143]
Is there any way we could disable horizontal scrollbars and use auto carriage return on lines, without incrementing the line numbers count?

**Comment by conorhastings** [comment]
@Sadkit sorry for the long time for response, I don't have the cycles for this but would be happy to offer advice or help sketch out an implementation plan

**Comment by conorhastings** [comment]
Right now since the numbers exists within the pre block if line numbers are on it would be possible with just css, could likely be achieved with more powerful lineProps
