### ISSUE TITLE
The prism classes concatenated  with ","

### ISSUE THREAD

**Issue by vorillaz** [conorhastings/react-syntax-highlighter#149]
**Describe the bug**
The output classes using Prism are concatenated with commas.

**To Reproduce**
```javascript
import React from 'react';
import {PrismAsyncLight as SyntaxHighlighter} from 'react-syntax-highlighter';

const V = `
  const pluckDeep = key => obj => key.split('.').reduce((accum, key) => accum[key], obj)

  const compose = (...fns) => res => fns.reduce((accum, next) => next(accum), res)

  const unfold = (f, seed) => {
    const go = (f, seed, acc) => {
      const res = f(seed)
      return res ? go(f, res[1], acc.concat([res[0]])) : acc
    }
    return go(f, seed, [])
  }
`;

export default ({value = '', language = 'javascript'}) => (
  <div>
    <SyntaxHighlighter language={language}>{V}</SyntaxHighlighter>
  </div>
);
```

**Expected behavior**
Get descriptive tokenize classes from the output React components.

**Screenshots**
<img width="849" alt="screen shot 2018-10-31 at 11 15 59 pm" src="https://user-images.githubusercontent.com/1022166/47819595-a1bfc300-dd63-11e8-8c04-bfb0632fdfa1.png">

**Desktop (please complete the following information):**
 - Version 10.0.0

**Comment by marcodejongh** [comment]
Hmm interesting, it doesn't seem to affect the rendering.
Looks like a issue with refractor to me, maybe create it there? https://github.com/wooorm/refractor
