### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by danilobjr** [conorhastings/react-syntax-highlighter#15]
How can I have custom styles? The natural way is using ```style``` prop or CSS classes, but we have ```style``` for theming and, in my project, I can't use css classes.

**Comment by conorhastings** [comment]
@danilobjr I've published `v2.3.0` which allows you to pass in a `customStyle` prop

**Comment by danilobjr** [comment]
@conorhastings Oh man! Thank you so much! =]
