### ISSUE TITLE
Path to styles

### ISSUE THREAD

**Issue by VladimirPittner** [conorhastings/react-syntax-highlighter#151]
**Describe the bug**
It seems that the path to the styles now is `react-syntax-highlighter/dist/styles/prism`, not the one that is in the example `react-syntax-highlighter/styles/prism`. 
Or did I do something wrong? :smile: 

**Version**
`"react-syntax-highlighter": "10.0.0",`

**Comment by marcodejongh** [comment]
Thanks @VladimirPittner , I've updated the readme and the changelog's.
