### ISSUE TITLE
How to highlight a diff

### ISSUE THREAD

**Issue by chasm** [conorhastings/react-syntax-highlighter#161]
**Is your feature request related to a problem? Please describe.**
I use this to teach. I need lines added/removed to be as clear as possible.

**Describe the solution you'd like**
I want to be able to include lines that are removed and lines that are added, where the removed lines are highlighted in red with a - to the left, and the added lines in green with a + to the left.

**Describe alternatives you've considered**
Other than forking this library, which I really haven't time to do, or using another, and there don't seem to be other options, none.

**Additional context**
Take a look at the Git diffs for pull requests for an example of what I'm talking about.

**Comment by marcodejongh** [comment]
> Other than forking this library, which I really haven't time to do, or using another, and there don't seem to be other options, none.

You probably mean well, but this line comes across as-if you don't have time to implement a diff so instead you're trying to have some open source maintainer do it for you for free.  

I don't have time to implement this feature either. But I'd happily discuss this feature with you to come up with a plan. First off I'm not entirely convinced it belongs in this module, but if it can be done elegantly enough I'd be open to it.

**Comment by chasm** [comment]
It's a feature suggestion. If there is no interest from others, then I certainly don't expect you to make the effort. But I'd be surprised if this wasn't something very useful to people. After all, tutorials are a common use of syntax highlighting.

If no one else wants to tackle it, then I'll either do it (happy to do a pull request if it works), or will give up on it and do without.

**Comment by conorhastings** [comment]
@chasm this demo needs to be updated to current api, but gives a decent idea of userland implementation -- https://github.com/conorhastings/react-syntax-highlighter/blob/master/demo/diff.js

**Comment by conorhastings** [comment]
closing as there is no action to be taken here, you can use the above example + attach a css class to line and add the + - in css
