### ISSUE TITLE
Syntax highlighter not working in my mobile

### ISSUE THREAD

**Issue by nandu-oooooooooooo** [conorhastings/react-syntax-highlighter#164]
****
Hello Everyone,
I have use react-syntax-highlighter in my react native project. Its was working of my virtual device successful using ('Nexus_6_API_27(AVD) - 8.1.0'). 
But when I used in real device (Redmi 4) so that are not work. 
**See virtual device screenshot**

![virtual-device](https://user-images.githubusercontent.com/46188768/50474435-bee4cc80-0975-11e9-86fc-7a5ca10accfb.png)

**See screenshot in my mobile**

![screenshot_2018-12-27-14-42-00-123_com code](https://user-images.githubusercontent.com/46188768/50474599-71b52a80-0976-11e9-9f5a-084b9e1231e5.png)

**See the following dependency in my project**
{
  "name": "Project_Name",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "link": "^0.1.5",
    "native-base": "^2.8.2",
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-gesture-handler": "^1.0.12",
    "react-native-markdown-renderer": "^3.2.8",
    "react-native-syntax-highlighter": "^2.0.0",
    "react-navigation": "^3.0.9"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.0",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

**And Code**
`
import React from 'react';
import { Text, View } from 'react-native';
import SyntaxHighlighter from 'react-native-syntax-highlighter'; // 2.0.0
import { tomorrow } from 'react-syntax-highlighter/styles/prism' // 7.0.1

export default class App extends React.Component {

  render() {
    return (
      <View style={{ backgroundColor: '#E87A90', height: '100%'}}>
        <Text style={{ marginTop: 30, marginBottom: 30, textAlign: 'center', fontSize: 22, fontWeight: '900' }}>React Native Syntax Higlighter</Text>
        <SyntaxHighlighter
          {...this.props}
          style={tomorrow}
          customStyle={{padding: 0, margin: 0 }}
          language='javascript'
          fontSize={18}
          highlighter="prism"
        >
         var x, y; / How to declare variables
         x = 5; y = 6;      // How to assign values
         z = x + y;         // How to compute values
        </SyntaxHighlighter>
      </View>
    );
  }
}
`
Please inform me, My app are under construction mode. and there are same problem are occur in other mobile device then we are not able to check every device manually.  and it will work on specific device so please notified me. Note that others are package are work fine in my mobile only this package are not working correctly.

**Comment by conorhastings** [comment]
please make issue in react-native-syntax-highlighter
