### ISSUE TITLE
Breaking change in patch version (10.1.1 -> 10.1.2): missing hljs language and styles imports in 10.1.2

### ISSUE THREAD

**Issue by davidcalhoun** [conorhastings/react-syntax-highlighter#166]
**Describe the bug**
These imports (and possibly more) cannot be resolved in `10.1.2`:

```js
import java from 'react-syntax-highlighter/languages/hljs/java';
import docco from 'react-syntax-highlighter/styles/hljs/docco';
```

Workaround: force downgrade to `10.1.1`

**To Reproduce**
1. View the error online here: https://codesandbox.io/s/6yjrw4y8z
2. Now click on `package.json` and change `10.1.2` to `10.1.1`, then observe the lack of an error.

**Comment by marcodejongh** [comment]
it's mentioned in the [changelog](https://github.com/conorhastings/react-syntax-highlighter/blob/master/CHANGELOG.MD#changed-1) that those references should be updated to: 

```
"react-syntax-highlighter/dist/esm/languages/hljs/java"
```

**Comment by davidcalhoun** [comment]
Thanks for the heads up, I'll update it.

From a consumer perspective, this is super surprising because it's a breaking change, which should be on a major version if this follows semver (e.g. `11.0.0`), so I could only update to the major version and expect to have to update the code.  It makes me hesitant to use this if a breaking change happens randomly on a patch version, when I don't expect to have to make any code changes.

**Comment by conorhastings** [comment]
Apologies, will be more careful in the future, there is not much we can do so i'm going to close but will be more cognizant in the future about things like this, thanks for the heads up
