### ISSUE TITLE
Isn't this library too heavy? Is there any other lightweight alternative?

### ISSUE THREAD

**Issue by ReactGirl** [conorhastings/react-syntax-highlighter#169]
This library uses the highlight.js as other dependencies witch I believe it's turn out a very heavy library.

      react-syntax-highlighter@^10.1.2:
      version "10.1.2"
      dependencies:
      highlight.js "~9.12.0"
      lowlight "~1.9.1"
      prismjs "^1.8.4"

Using [Source map explorer Analyzer](https://www.npmjs.com/package/source-map-explorer)  demonstrates that it's add 674kb to the build plus 154kb of the library itself. As comparison, the library lodash.js adds 74kb to the build process.

<img width="532" alt="screenshot 2019-01-13 at 09 18 57" src="https://user-images.githubusercontent.com/29104515/51083565-48d1bb00-1714-11e9-8d53-ad45105024ac.png">

Is there any other alternatives for just display a code with highlighting ?
I'm the only one that feels that this library is too heavy?

**Comment by conorhastings** [comment]
could you share a code snippet, you can likely optimize the build output as i see you're including all of styles.

**Comment by dmtrKovalenko** [comment]
@ReactGirl source-map explorer not really best way to get the bundle size. 

First of all by default this lib doesn't build all languages and styles in the bundle. You must make lazy import for them. Check my own bundle analyzer for created bundle. 
![image](https://user-images.githubusercontent.com/16926049/51104942-3f1d8580-17f0-11e9-84df-40e8942908ac.png)

**Comment by ReactGirl** [comment]
Yes, I think the probably is with the highlight importing all languages and stuff.
Anyway, I found this library as an alternative with much fewer dependencies and works out of the box

[https://github.com/rahulbhooteshwar/snippet-highlight](https://github.com/rahulbhooteshwar/snippet-highlight)

**Comment by conorhastings** [comment]
@ReactGirl depending on your needs you likely would want to use the light version, that library works and if it fits your needs that's great

This library aims to provide more functionality and styling options via js objects from prism or hljs

It could also be your build setup not respecting esm

**Comment by sendmenas** [comment]
@ReactGirl I had the same issue. After doing some research I found the way how to import only a light build. Using "import { Light as SyntaxHighlighter } from "react-syntax-highlighter";" didn't worked as expected, but this did the trick:

```
import SyntaxHighlighter, { registerLanguage } from 'react-syntax-highlighter/dist/light'
import php from 'react-syntax-highlighter/dist/languages/hljs/php'

registerLanguage('php', php)
```

**Comment by DavidSichau** [comment]
@sendmenas This stopped working for me in version 10.2.1. Does this apply also for you?

**Comment by sendmenas** [comment]
> @sendmenas This stopped working for me in version 10.2.1. Does this apply also for you?

@DavidSichau not working on the project that used that lib anymore, so I don't know :/
