### ISSUE TITLE
Option to use standard style sheets / class names

### ISSUE THREAD

**Issue by JakeSidSmith** [conorhastings/react-syntax-highlighter#17]
Hey, there.

Was really happy to see that someone had finally made an actual React syntax highlighter, not using dangerouslySetInnerHTML or other such undesirable methods. Good job.

I was, however, quickly disappointed when I saw that this uses inline styles, and inline styles only.

I am not a fan of this method of styling, there are numerous downsides over using standard CSS.

I was hoping to use react-syntax-highlighter for the documentation for my [latest library](https://github.com/JakeSidSmith/react-style-sheets) that hopes to remove the need / want for inline styles completely... so you can see how using react-syntax-highlighter for the documentation would be kind of contradictory.

Is there any chance you could add the ability to choose to use either inline styles, or class names? Unfortunately until such a feature is added, I cannot use this library.

**Comment by conorhastings** [comment]
@JakeSidSmith pubished `2.4.0` this allows you to pass in the prop `useInlineStyles={false}` and then use a css stylesheet from highlight.js

**Comment by JakeSidSmith** [comment]
Wow, that was an incredibly quick response and resolution. Thanks a lot, I'll check it out. :)
