### ISSUE TITLE
Logging scroll events

### ISSUE THREAD

**Issue by soEricNG** [conorhastings/react-syntax-highlighter#170]
I'm using this component for a code review tool that I have developed. I would love to send logs every time the user scroll on the this component to see how much of the code the user is reading. However, I can't figure out a way to do it. Basically, I would like to call a backend API for the onScroll event. What can I do?

Thank you!

p.s.  I absolutely love this component. This is more of a help post than an issue, but I just couldn't find another medium for this.

**Comment by marcodejongh** [comment]
I'd recommend asking this question on stackoverflow, the solution most likely doesn't involve anything done to react-syntax-highlighter (assuming it's the window that's overflowing not the highlighter).
In which case you probably want a onscroll event on window and determine what's in view in that event. Either way: Stackoverflow 😄
