### ISSUE TITLE
new hljs themes

### ISSUE THREAD

**Issue by Superpencil** [conorhastings/react-syntax-highlighter#175]
hljs 9.13.0 has introduced a bunch of new themes that are lovely, and I'd love to see them in react-syntax-highlighter 🙇🏻‍♂️

**Comment by conorhastings** [comment]
updated and added in `v10.2.0` 

thanks!

**Comment by Superpencil** [comment]
Thanks Conor!

**Comment by Superpencil** [comment]
@conorhastings the styles in the new update seem to be in `/esm/styles/**.js` and `/cjs/styles/**.js` while `/dist/styles/**.js` has not been updated, is that intentional or a bug? 😅

**Comment by conorhastings** [comment]
@Superpencil this is intentional, was a breaking change in v10, old files on my computer are still being published, will publish a new version without dist/styles later tonight, thanks

**Comment by Superpencil** [comment]
@conorhastings Alrighty then!
