### ISSUE TITLE
Usage of useInlineStyles

### ISSUE THREAD

**Issue by Colman** [conorhastings/react-syntax-highlighter#179]
How can I append my own className to the SyntaxHighlighter element? Not one from highlight.js or prism but a css class from my own project. I tried setting useInlineStyles={false} and customStyle="my-css-class" but nothing happened.

**Comment by conorhastings** [comment]
@Colman customStyle would be a style object not a classname, to pass in a className you should be able to do it directly.

**Comment by conorhastings** [comment]
closing, can reopen if question persists
