### ISSUE TITLE
Webpack upgrade yields loader error

### ISSUE THREAD

**Issue by TimVanMourik** [conorhastings/react-syntax-highlighter#182]
**Describe the bug**
I'm a happy user of `react-syntax-highlighter` and would like to report an issue that I encountered. I recently run an `npm update` in my react app in which the `webpack` dependency was upgraded from `4.28.0` to `4.30.0`. This caused a compilation error that traces back to `react-syntax-highlighter`:

```
ERROR in ../node_modules/react-syntax-highlighter/dist/esm/light-async.js 5:11
Module parse failed: Unexpected token (5:11)
You may need an appropriate loader to handle this file type.
| export default createAsyncLoadingHighlighter({
|   loader: function loader() {
>     return import(
|     /* webpackChunkName:"react-syntax-highlighter/lowlight-import" */
|     'lowlight/lib/core').then(function (module) {
 @ ../node_modules/react-syntax-highlighter/dist/esm/index.js 2:0-54 2:0-54
 @ [...my react files]
```
**To Reproduce**
In a React app with `react-syntax-highlighter` and `webpack` as dependencies, upgrade the `webpack` dependency from `4.28.0` to `4.30.0`. 

**Expected behavior**
No errors on compilation

**Desktop:**
 - Docker: `FROM node:9`
- `react-syntax-highlighter@10.2.1`

**Additional context**
I'm a relative newbie to react, babel, and loaders, so I'm not sure what information is relevant. Happy to provide more on request.

The error explicitly says: "You may need an appropriate loader to handle this file type." but I haven't been able to find any. I'm happy to help out in searching for a solution, but I'm a bit of a newbie so I will need some pointers. 

I hope this is useful to improving your brilliant software :)

**Comment by conorhastings** [comment]
I found this issue that might help -- https://github.com/webpack/webpack/issues/8656 -- only had a chance to peruse quickly though, can give a more in depth look later

**Comment by TimVanMourik** [comment]
Thanks for the prompt response. I had found that solution (`npm update acorn --depth 20`) and followed the solution, but it did not resolve the problem. Hence my suspicion it the bug was in this repo, as it was the only one in my dependencies that was acting up. 
 
On closer inspection though, the reason seems to be issues for npm@5 described in  https://github.com/npm/npm/issues/19045 and https://github.com/npm/npm/issues/20173, causing the solution not to work. I haven't quite been able to solve the problem, but it's clear it's my problem, not this repo's :) Apologies for the false alarm.

**Comment by wugaoliang1116** [comment]
my project webpack version's 4.29.4;  
I had found that solution (`npm install webpack@4.28.4`);
successfully !!!
Hopefully this will work for others.
