### ISSUE TITLE
Add VS Code Style

### ISSUE THREAD

**Issue by karlhorky** [conorhastings/react-syntax-highlighter#184]
First of all, thanks for this project! Great to see more tools for highlighting in the React ecosystem.

**Is your feature request related to a problem? Please describe.**

It would be nice to be able to highlight code in the default style of VS Code (dark theme). Similar to that in `prism-react-renderer` (eg. FormidableLabs/prism-react-renderer#28).

**Describe the solution you'd like**

A style for VS Code (dark theme).

**Describe alternatives you've considered**

Generation of the theme using a generator tool like [this](https://github.com/FormidableLabs/prism-react-renderer/tree/master/tools/themeFromVsCode). I didn't find one in the readme though.

**Additional context**

Screenshot of VS Code (dark theme):

<img src=https://user-images.githubusercontent.com/1935696/53699580-373e9280-3dea-11e9-8798-acd1ff328ea1.png>

**Comment by conorhastings** [comment]
added in 10.3.0 , will work on adding similar function to automate process in the future

**Comment by karlhorky** [comment]
Oh wow, that was quick! Thanks!
