### ISSUE TITLE
Async Highlight: Super expression must either be null or a function

### ISSUE THREAD

**Issue by tschellenbach** [conorhastings/react-syntax-highlighter#190]
- inherits.js:5 Uncaught TypeError: Super expression must either be null or a function
    at _inherits (inherits.js:5)
    at eval (async-syntax-highlighter.js:44)
    at eval (async-syntax-highlighter.js:168)
    at eval (light-async.js:6)

Happens when importing like this while running webpack in development mode:

```
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { atomDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
```

Build stack: webpack: 4.33,.0, babel 7.4.5
Command: webpack --mode development --watch

**Comment by conorhastings** [comment]
is that the only code in the file ?

**Comment by conorhastings** [comment]
please reoopen if above addressed
