### ISSUE TITLE
Autogrenerated Language Imports

### ISSUE THREAD

**Issue by jclangst** [conorhastings/react-syntax-highlighter#191]
**Is your feature request related to a problem? Please describe.**
It looks like the current language bindings to the upstream libraries like refractor are manually generated. As a result, this library is missing some recent additions to those upstream libs.

**Describe the solution you'd like**
Instead of manually generating them, since the imports/bindings are so generic, we could have a pre-publish or pre-commit script that runs automatically, ensuring these stay in sync without having to worry. Would you be interested in either of those paths? I could certainly take that on if so.

**Comment by conorhastings** [comment]
there generated automatically on publish if you look at the build language scripts, possibly just delayed publishing or versioning? Unless I'm misunderstanding you, please feel free to correct

**Comment by jclangst** [comment]
Ah. I see that you have pretty much exactly what I was suggesting. I was confused by the language files being included in git. My bad.
