### ISSUE TITLE
why only the first line hightlighted?

### ISSUE THREAD

**Issue by BinghuiXie** [conorhastings/react-syntax-highlighter#197]
Heres my code:
![image](https://user-images.githubusercontent.com/34343589/60789798-89c1fe00-a192-11e9-8930-6f36bac8f716.png)
and here is the hightlighted code:

![image](https://user-images.githubusercontent.com/34343589/60789854-aa8a5380-a192-11e9-9a14-5a117a88bd76.png)
troubles me a lot

**Comment by conorhastings** [comment]
can you paste the text, it will likely be easier to debug

**Comment by conorhastings** [comment]
please reopen if question above addressed, thanks.
