### ISSUE TITLE
Show how to add grammars

### ISSUE THREAD

**Issue by wooorm** [conorhastings/react-syntax-highlighter#2]
Is there some method to add a grammar to the highlighter? Also: [this doc on lowlights repo](https://github.com/wooorm/lowlight#lowlight-in-the-browser)

**Comment by conorhastings** [comment]
@wooorm what do you mean by add a grammar? sorry, the reason i went against the direction of that piece of documentation is that i wanted to make all languages available for highlighting, do you have another suggestion? Dynamically require them perhaps based on users need?

**Comment by wooorm** [comment]
I’d say users need to specify them themselves, otherwise it 530kb of code is included on the client, which I don’t think is ever a good idea!

**Comment by conorhastings** [comment]
@wooorm agreed, i'll look into updating this tonight!

**Comment by wooorm** [comment]
:+1:

**Comment by conorhastings** [comment]
im using dynamic requires with webpack, this means webpack will be required for nwo but should cut down on package size will test a build soon.

**Comment by wooorm** [comment]
@conorhastings Ping (:

**Comment by conorhastings** [comment]
@wooorm you should be able to pass a grammar with the `language` prop, and with the dynamic require it should only actually end up requiring what you are using I think, very busy at work so still haven't had time to test package sizes.
