### ISSUE TITLE
vue syntax support

### ISSUE THREAD

**Issue by KutnerBitsrc** [conorhastings/react-syntax-highlighter#207]
I am using **react-syntax-highlighter** with **Prismjs**.
for most syntaxes it works out of the box, but not for Vue Templates.

it's possible to add languages via ```SyntaxHighlighter.registerLanguage()```, but where can I find definition for Vue?

**Comment by conorhastings** [comment]
i would need to be a supported language of prism https://prismjs.com/#supported-languages

**Comment by KutnerBitsrc** [comment]
ok, after some searching, it doesn't seem to be any support for Vue, both officially and by extension.
https://github.com/PrismJS/prism/issues/1665

The format is called 'Single File Component'.
https://vuejs.org/v2/guide/single-file-components.html

😢

**Comment by conorhastings** [comment]
perhaps comment here -- https://github.com/PrismJS/prism/issues/1665
