### ISSUE TITLE
Add support for line numbers

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [conorhastings/react-syntax-highlighter#22]
You should be able to automatically show line numbers via a `showLineNumbers` prop, and, additionally, you should be able to say what line number to start at (`firstLineNumber`?).

This would be very useful for when you want to show an entire file, but you want to put other things (like code review comments perhaps) between lines.

**Comment by twe4ked** [comment]
I'd love this feature. It would be great if you could specify an element to wrap each line. That way you could add line numbers and/or row highlighting.

**Comment by conorhastings** [comment]
@twe4ked I think an element to wrap each line is a bit more difficult than line numbers, since the number of dom elements on each line isn't defined and the spacing is achieved by the fact the pre respects white space/new lines

**Comment by twe4ked** [comment]
Yeah I thought that might be the case. It also gets tricky with highlights that go over multiple lines.

**Comment by conorhastings** [comment]
@PaulJuliusMartinez @twe4ked do you want to take a look at #27 and let me know what you think?

<img width="647" alt="screen shot 2016-10-02 at 8 27 38 pm" src="https://cloud.githubusercontent.com/assets/8263298/19024980/b120113c-88de-11e6-9242-6e85a70fcad0.png">

**Comment by conorhastings** [comment]
published the line numbers in `2.8.0`
