### ISSUE TITLE
How to you change the Text font size ?

### ISSUE THREAD

**Issue by tjtaill** [conorhastings/react-syntax-highlighter#222]
This is a great project super grateful but having difficulty figuring how I set the text font size for this widget, I figure it is a nested prop somewhere but not sure where, I have found an example of setting the font family but not the size ?

**Comment by tjtaill** [comment]
sorry
codeTagPros = {
  fontSize: "16",
}

works fine closing

**Comment by tjtaill** [comment]
Sorry that did not do it, tried
customStyle = {
  lineHeight: 0.75
}

didn't work either need to find where to put fontSize or lineHieght to make the text/code box more compressed

**Comment by tjtaill** [comment]
This is how I finally got it to work

customStyle = {
lineHeight: "0.75",
fontSize: "1em"
}

codeTagProps =  {
  style: {
    lineHeight: "inherit",
    fontSize: "inherit"
  }
}

Hope this helps someone else

**Comment by softmarshmallow** [comment]
Line height does not work below 1.
