### ISSUE TITLE
lineStyle was replaced by lineProps but documentation/demo is incorrect

### ISSUE THREAD

**Issue by Roeefl** [conorhastings/react-syntax-highlighter#224]
Hello,

Apparently you've replaced the prop `lineStyle` by `lineProps`.

However, the example at http://conorhastings.github.io/react-syntax-highlighter/demo/diff.html is still using `lineStyle`

Attempting to use `lineProps` in a similar fashion, or in any other fashion, does not seem to work when trying to apply custom styling to each line.

Thank you

**Comment by conorhastings** [comment]
can you post example code please

**Comment by Roeefl** [comment]
Not sure what you mean bro,

On your own example code here:
http://conorhastings.github.io/react-syntax-highlighter/demo/diff.html

If you try to run it, you'd get
`Warning: React does not recognize the `lineStyle` prop on a DOM element.`

**Comment by Roeefl** [comment]
I'm just asking how to use lineProps in a similar fashion since I could only find this:

`lineProps - props to be passed to the span wrapping each line if wrapLines is true. Can be either an object or a function that receives current line number as argument and returns props object.`

But I can't seem to use it in the way you'd intended

Thanks

**Comment by camendoza94** [comment]
See this PR #220

**Comment by Roeefl** [comment]
Thank you.
