### ISSUE TITLE
SyntaxError: Unexpected token export when using NextJS

### ISSUE THREAD

**Issue by Vista1nik** [conorhastings/react-syntax-highlighter#230]
**Describe the bug**
Error appears when I trying to import any react-syntax-highlighter styles in NextJS app.

**To Reproduce**
1. Create NextJS app using 'create-next-app'
2. Import any react-syntax-highlighter style.

**Expected behavior**
Working Syntax Highlight.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Chrome
 - Version: 77

**Additional context**
Full error message:
```
Unexpected token export
/home/vista1nik/Documents/es-snippets/node_modules/react-syntax-highlighter/dist/esm/styles/hljs/index.js:1
export { default as a11yDark } from './a11y-dark';
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.react-syntax-highlighter/dist/esm/styles/hljs (/home/vista1nik/Documents/es-snippets/.next/server/static/development/pages/index.js:2563:18)
    at __webpack_require__ (/home/vista1nik/Documents/es-snippets/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index.js (/home/vista1nik/Documents/es-snippets/.next/server/static/development/pages/index.js:2156:104)
    at __webpack_require__ (/home/vista1nik/Documents/es-snippets/.next/server/static/development/pages/index.js:23:31)
    at Object.4 (/home/vista1nik/Documents/es-snippets/.next/server/static/development/pages/index.js:2320:18)
    at __webpack_require__ (/home/vista1nik/Documents/es-snippets/.next/server/static/development/pages/index.js:23:31)
    at /home/vista1nik/Documents/es-snippets/.next/server/static/development/pages/index.js:91:18
    at Object.<anonymous> (/home/vista1nik/Documents/es-snippets/.next/server/static/development/pages/index.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
```

**Comment by scottsgcho** [comment]
Getting the same issue

**Comment by malithmcr** [comment]
I'm having the same issue.

**Comment by conorhastings** [comment]
@malithmcr @scottsgcho @Vista1nik do any of you have a repo with the error

**Comment by sidujjain** [comment]
you can fix the issue using `next-transpile-modules` but it doesn't seem to do tree-shaking. 

Something like this in `next.config.js`: 
```
const withTM = require("next-transpile-modules");
const withPlugins = require("next-compose-plugins");

module.exports = withPlugins(
  [
    [
      withTM,
      {
        transpileModules: [
          "react-syntax-highlighter",
        ]
      }
    ],
    ...
```

**Comment by zemuldo** [comment]
@sidujjain Following your advice and https://www.npmjs.com/package/next-transpile-modules docs helped. Thanks!

**Comment by sidujjain** [comment]
you're welcome @zemuldo! 

Actually I found a better solution. You just need to use `cjs` module. 

`react-syntax-highlighter/dist/cjs/...`
instead of:
`react-syntax-highlighter/dist/esm/...`

And you won't have to use `next-transpile-modules`.

**Comment by SalahAdDin** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...`
> instead of:
> `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

It didn't work for me.

**Comment by Preshonyee** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...`
> instead of:
> `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

this works for me...after loads of trial and error

**Comment by matiasherranz** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...`
> instead of:
> `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

This worked for me! Thanks for sharing!

**Comment by mkkeffeler** [comment]
huge save, worked for me #opensource for the win

**Comment by f3ve** [comment]
@SalahAdDin Thanks for the simple fix!

**Comment by faustinozanetto** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...`
> instead of:
> `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

Man you deserve something, thanks a lot

**Comment by Mikeultron** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...`
> instead of:
> `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

Not all heroes wear capes

**Comment by dev-mdminhaj** [comment]
Try to access from node_modules. It's worked!
for example : `/node_modules/react-syntax-highlighter/dist/esm/styles/prism';`

**Comment by DumasOlivier** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...`
> instead of:
> `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

Thank you so much @sidujjain it worked ! 😍

**Comment by padunk** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...`
> instead of:
> `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

Thanks for the solution.
Can we update and add this on the docs  please? Thanks.

**Comment by kimbaudi** [comment]
@padunk - I've submitted a PR to update the README.

**Comment by cazterk** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...` instead of: `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.


awesome awesome awesome

**Comment by michaelsong4399** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...` instead of: `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

Works for me! Thank you for this solution!

**Comment by Nightvision53** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...` instead of: `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

Thanks It worked for me.

**Comment by SujalShah3234** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...` instead of: `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

This works but at cost of bundle size 💀

**Comment by masoudteymuri** [comment]
> [sidujjain](/sidujjain)

Hi friends, I had the same problem and our friend @sidujjain solved the problem, but the whole package size will be added to your component. To solve this problem, use this:
import dark from "react-syntax-highlighter / dist / cjs / styles / prism / dark";

**Comment by AidanLDev** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...` instead of: `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

Worked a charm, thank you

**Comment by kingRayhan** [comment]
> > you're welcome @zemuldo!
> > Actually I found a better solution. You just need to use `cjs` module.
> > `react-syntax-highlighter/dist/cjs/...`
> > instead of:
> > `react-syntax-highlighter/dist/esm/...`
> > And you won't have to use `next-transpile-modules`.
> 
> This worked for me! Thanks for sharing!

You saved my life

**Comment by xylvnking** [comment]
> > [sidujjain](/sidujjain)
> 
> Hi friends, I had the same problem and our friend @sidujjain solved the problem, but the whole package size will be added to your component. To solve this problem, use this: import dark from "react-syntax-highlighter / dist / cjs / styles / prism / dark"; Instead of using this: import {dark} from "react-syntax-highlighter / dist / cjs / styles / prism ";

This fixed it for me!

**Comment by Schachte** [comment]
Full working solution

```javascript
import React from "react";

import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import d from "react-syntax-highlighter/dist/cjs/styles/prism/nord";

const CodeBlock = {
  code({ node, inline, className, children, ...props }) {
    const match = /language-(\w+)/.exec(className || "");
    return !inline && match ? (
      <SyntaxHighlighter
        style={d}
        language={'javascript'}
        PreTag="div"
        showLineNumbers={true}
        customStyle={{ margin: 0, padding: ".8rem" }} 
        {...props}
      >
        {String(children).replace(/\n$/, "")}
      </SyntaxHighlighter>
    ) : (
      <code className={className + " "} {...props}>
        {children}
      </code>
    );
  },
};

export default CodeBlock;
```

**Comment by thesatishjassal** [comment]
> Try to access from node_modules. It's worked on NextJs project! for example : `/node_modules/react-syntax-highlighter/dist/esm/styles/prism';`

working thx

**Comment by zesertebe** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...` instead of: `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

You are the best. You saved my life. Whenever you want I'll buy you a beer or whatever you want.

**Comment by dnldmp** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...` instead of: `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

Thank you it help me a lot :D

**Comment by PiseAtharva** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...` instead of: `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.

thanks a lot, helped me a lot for this OS project

**Comment by masonictemple4** [comment]
> you're welcome @zemuldo!
> 
> Actually I found a better solution. You just need to use `cjs` module.
> 
> `react-syntax-highlighter/dist/cjs/...` instead of: `react-syntax-highlighter/dist/esm/...`
> 
> And you won't have to use `next-transpile-modules`.


A couple years late, and this still worked! Thanks for sharing :pray:
