### ISSUE TITLE
for react native?

### ISSUE THREAD

**Issue by cinder92** [conorhastings/react-syntax-highlighter#25]
Hello is there any plan to build this for react-native?

thanks!

👍

**Comment by conorhastings** [comment]
not currently supported but i don't think it would be to difficult. Would just need to map tagnames / style properties should basically be the same.

**Comment by vyky** [comment]
Looking forward for react native :thumbsup:

**Comment by conorhastings** [comment]
@cinder92 @vyky it's been a while but i finally got around to having time to work on this, published as a seperate package -- https://github.com/conorhastings/react-native-syntax-highlighter
