### ISSUE TITLE
lineProps object should not be modified

### ISSUE THREAD

**Issue by gediminasel** [conorhastings/react-syntax-highlighter#252]
**Describe the bug**
https://github.com/conorhastings/react-syntax-highlighter/blob/master/src/highlight.js#L101
`className` is added directly to `lineProps` object therefore list of class names persist through lines and keeps growing. 

**To Reproduce**
1. Use SyntaxHighlighter to highlight code with multiline comments
2. Set `wrapLines={true}`
3. Pass object or `undefined` as `lineProps`
4. Code after multiline comment is highlighted as comment

**Expected behavior**
Code after comment should use default foreground color.

**Screenshots**
Current:
![image](https://user-images.githubusercontent.com/21194519/77313800-33d7bb00-6d0d-11ea-8d0d-7a62026035bb.png)

Expected:
![image](https://user-images.githubusercontent.com/21194519/77313774-26bacc00-6d0d-11ea-8cc8-b5f0749f2327.png)

**Comment by simmerer** [comment]
Pretty sure I introduced this one. Thanks for calling this out! I'll get on it.

**Comment by simmerer** [comment]
Resolved in upcoming `13.0.0` release.
