### ISSUE TITLE
Latest release does not reflect master

### ISSUE THREAD

**Issue by phoenisx** [conorhastings/react-syntax-highlighter#254]
Hi! I see that master says, `toml` is supported, but the last release was done 4 months ago. Pardon me, if this is not the right place to post this kind of issue, but I just wanted to know when is the latest release happening and how do you release your code?

I really am in need for `toml` syntax, which I see is already supported, but not yet published.

Thanks.

**Comment by simmerer** [comment]
Hello! Conor's been swamped with other stuff, so I'm pitching in to help. Working on prepping a 13.0.0 release which will contain the past few months' updates. Sorry for the delay!

**Comment by simmerer** [comment]
Just waiting on publish to npm: https://github.com/conorhastings/react-syntax-highlighter/issues/275

**Comment by conorhastings** [comment]
13.0 released thanks @simmerer
