### ISSUE TITLE
Mixing js and jsx renders some tags in a wrong way

### ISSUE THREAD

**Issue by SalahAdDin** [conorhastings/react-syntax-highlighter#271]
**Describe the bug**
I'm trying to render a normal javascript file which includes both `js` and `jsx`:
```jsx
import { useState } from "react"
import PropTypes from "prop-types"
import ReactMarkdown from "react-markdown"
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter"

// import RemarkHighlightPlugin from "remark-highlight.js"
// import RemarkMathPlugin from "remark-math"
// import { BlockMath, InlineMath } from "react-katex"

import oceanic from "@/styles/material-oceanic"

const CodeBlock = ({ language, value }) => (
  <SyntaxHighlighter
    showLineNumbers={true}
    startingLineNumber={1}
    language={language}
    style={oceanic}
    lineNumberContainerProps={{
      style: { color: "#ddd", paddingRight: "1.625em", float: "left" },
    }}
    wrapLines={true}
  >
    {value}
  </SyntaxHighlighter>
)
```

**To Reproduce**
To see this we just normally render the content.
1. Insert some of code in the editor(who's gets it as markdown).
2. Go to the main page.
3. Look in the content section

**Expected behavior**
We should see something like:
![originalcode](https://user-images.githubusercontent.com/5034215/87416200-07ef8680-c5d7-11ea-8308-cdfc3940b4ed.png)
Properly colored by pairs.

**Screenshots**
Instead, we can see the pairing tags are not colored equal:
![Screen Capture_select-area_20200714012609](https://user-images.githubusercontent.com/5034215/87416423-5a30a780-c5d7-11ea-9b64-cb078bec3c4b.png)
As you can see, some tags which it does not know if they are or not it uses `maybe` class name, but in one place it uses a correct color while in another place it does not.

While, when it is just rendering pure `jsx`, it renders correctly:
![Screen Capture_select-area_20200714012653](https://user-images.githubusercontent.com/5034215/87416301-2b1a3600-c5d7-11ea-97b6-e5d99e08a328.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Chromium
 - Version 83.0.4103.97 (Official Build) Arch Linux (64-bit)

**Comment by simmerer** [comment]
Hello! Could you show your syntax-highighting code that's producing what we're seeing above? My guess is that your code isn't including a `language` prop.

**Comment by SalahAdDin** [comment]
It seems you are right, i tried it today and i didn't found that error, i will close this bug.

I will reopen it if i see it again.

@simmerer Thanks.

**Comment by simmerer** [comment]
Thank you!
