### ISSUE TITLE
Provide interface to low.highlightAuto(), to auto-guess the language

### ISSUE THREAD

**Issue by stefanheine** [conorhastings/react-syntax-highlighter#29]
I wonder if there is a way to use react-syntax-highlighter without providing the language information, internally making a call to low.highlightAuto(), guessing the language/ grammer from the provided source code.

**Comment by conorhastings** [comment]
@stefanheine yes I believe this shouldn't be too difficult (though it wouldn't work if you were using the light entry point) we could hook in here - https://github.com/conorhastings/react-syntax-highlighter/blob/master/src/highlight.js#L67 if no language is provided as long as we check that highlightAuto is available

**Comment by conorhastings** [comment]
@stefanheine published `2.9.0` with this
