### ISSUE TITLE
Lots of styles missing a background color

### ISSUE THREAD

**Issue by jonrimmer** [conorhastings/react-syntax-highlighter#31]
A large number of the styles have no defined background color, e.g. ardunio-light, arta, brown-paper, color-brewer, etc.

This can be seen by selecting on one of these styles on the demo page.

**Comment by conorhastings** [comment]
@jonrimmer thanks for the report! this should be fixed in `2.10.0` , you can check the demo page - http://conor.rodeo/react-syntax-highlighter/demo/ - and try it out!

**Comment by jonrimmer** [comment]
Looking good! Great project btw :-)

**Comment by conorhastings** [comment]
thanks!
