### ISSUE TITLE
Build size - Lowlight dependency

### ISSUE THREAD

**Issue by coljung** [conorhastings/react-syntax-highlighter#34]
I was analyzing my bundle size with this tool: https://chrisbateman.github.io/webpack-visualizer/

It results show that node_modules are around 95% of my bundle size, and out of that 95%, 28% is taken by lowlight.

I see that you have a Light Build option, but im not sure how this would impact my final bundle size if i still have to load lowlight for it to work.

Is there a big reduction related to how lowlight manages the code if i choose the Light Build way ? 

Thanks!

**Comment by conorhastings** [comment]
@coljung Yes the light build will allow you to only bring in the languages you use instead of all of the languages supported by highlight.js resulting in a drastically reduced bundle size. I was personally able to see a 10x package size drop - https://github.com/conorhastings/react-syntax-highlighter/issues/13#issuecomment-236432870

**Comment by coljung** [comment]
Thanks for the quick response, will try implementing the light build then.

**Comment by bmathews** [comment]
@coljung Here's an example  importing the light version and only the JS language, without needing `webpack.definePlugin`. 

```
import SyntaxHighlighter from "react-syntax-highlighter/dist/light";
import lowlight from 'lowlight/lib/core';
import js from 'highlight.js/lib/languages/javascript';
lowlight.registerLanguage('javascript', js);
```

**Comment by coljung** [comment]
@bmathews Yep, thx, thats the setup i have now. 

If i try running the webpack visualizer tool, lowlight doesnt show up anymore ( very small footprint so it's not visible without having to zoom in!

So it went from over 700k to around 40k.
