### ISSUE TITLE
the line number is wrong when i have a long line

### ISSUE THREAD

**Issue by liuxin1017** [conorhastings/react-syntax-highlighter#42]
the line number is wrong when i have a long line, it will be counted as two line

**Comment by conorhastings** [comment]
can you provide an example. Thanks!

**Comment by conorhastings** [comment]
closing for now, will reopen if example can be provided.

**Comment by mjomble** [comment]
This can happen when using something other than `pre` as `PreTag` or applying a style like `white-space: pre-wrap`, etc.

Would be nice if this component allowed wrapping long lines without messing up the line number alignment, but that sounds like a tricky task :)

**Comment by conorhastings** [comment]
@mjomble feel free to create an issue about that and i'll happily look into it, please provide code if possible
