### ISSUE TITLE
Provide ability to make contentEditable

### ISSUE THREAD

**Issue by kyleknighted** [conorhastings/react-syntax-highlighter#45]
This is probably one of the cleanest methods of syntax highlighting I've found that is easy to style and uses popular open source technology.
My biggest issue is that I can't use it because I need to be able to edit the highlighted code.

Maybe one day I'll find myself with enough free time to dig into that, but if you have that in the works, it would be an awesome introduction to this library.

**Comment by conorhastings** [comment]
you should be able to pass in contentEditiable as a prop that will get spread to the component, in the past i've had issues with overwhelming React warnings in regards to contentEditible but have successfully implemented things like this - https://github.com/conorhastings/react-component-demo/blob/master/src/index.js#L53 - on top of this module. Let me kwnow if this helps.

**Comment by kyleknighted** [comment]
Yea, I was able to kill off those React warnings with a snippet like
```js
console.error = (function() {
    var error = console.error

    return function(exception) {
        if ((exception + '').indexOf('Warning: A component is `contentEditable`') != 0) {
            error.apply(console, arguments)
        }
    }
})()```

but I wasn't able to figure out the best way to get the content to re-do highlighting after typing something.

**Comment by conorhastings** [comment]
I don't think we'll add support for this in library, if anyone finds a good solution i'd be happy to showcase a demo though
