### ISSUE TITLE
Hook events

### ISSUE THREAD

**Issue by gala132** [conorhastings/react-syntax-highlighter#49]
Hi!

Is there a way to hook on the render events or any events?
If I have a longer code of html for example rendering, then it takes a lot of time and the UI is blocking that way so the best would be if I could hook on the event when the rendering of the code is finished and display a loader in the meanwhile.

**Comment by conorhastings** [comment]
so you basically want to be able to hook into componentDidMount and componentDidUpdate events so you can know when a render has occurred?

What do you think of #50

**Comment by gala132** [comment]
The problem right now is the following:
I would like to be able to display a loading bar while the string is rendering somehow.
Now the problem is that I have a very long html string and when I display it in the Syntaxhighlighter elements, it takes 5-7 seconds to render it highlighted so I would like to be able to display a bar while it is rendered. Right now it just blocks the UI for the time it is rendered so either a hook or some other processing would be good to let the user know about the process. (maybe something async for rendering?)

**Comment by conorhastings** [comment]
React does not really provide the exact mechanics you're looking for but depending on. I haven't tried this myself but if this component allowed hooking into component lifecycles methods as illustrated in #50 something like this should work:

```
class MyCode extends React.Component {
  constructor() {
    super();
    this.state = { codeRendering: true, longHTMLString: `<html>...</html>` };
  }
  render() {
    const loader = this.state.condeRendering ? <Loader /> : null;
    return (
      <div>
        {loader}
        <SyntaxHighlighter 
          language='html'
          style={docco}
          componentWillReceiveProps={function(nextProps) {
            /* using call in syntax highlighter so this will represent this of syntax component 
                make sure not to use arrow function if you need this, this is not bound for arrow functions
            */
            if (nextProps.children !== this.props.children) {
              this.setState({ codeRendering: true });
            }
          }}
          componentDidMount={() => this.setState({ codeRendering: false })}
          componentDidUpdate={() => this.setState({ codeRendering: false })}
        >
          {this.state.longHTMLString}
        </SyntaxHighlighter>
      </div>
    );
  }
}
```

**Comment by conorhastings** [comment]
alternatively (since i'm not entirely suer i want api complexity of #50) just create a wrapper component for syntax highlighter in your app and implement these methods, since children are guaranteed to render first you can be sure the syntax highlighting will have rendered.

**Comment by gala132** [comment]
If i make it like you proposed to (Add the componentWillReceiveProps, componentDidMount, componentDidUpdate on the element) it displays an error and does not work like you described it.
The error is the following:
`Warning: Unknown props `componentWillReceiveProps`, `componentDidMount`, `componentDidUpdate` on <pre> tag.`

**Comment by conorhastings** [comment]
@gala132 sorry that code was just meant as a hypothetical possibility if #50 was merged. I think though it's not worth the added complexity in core, you should be able to solve in userland with a wrapper around this component, something like this

```jsx
class SyntaxWrapper extends React.Component {
  constructor() {
    super();
    this.state = { codeRendering: true };
  }
  componentDidMount() {
    this.setState({ codeRendering: false });
  }
  componentWillReceiveProps(nextProps) {
    if (nextProps.children !== this.props.children) {
      this.setState({ codeRendering: true });
    }
  }
  componentDidUpdate() {
    if (this.state.codeRendering) {
      this.setState({ codeRendering: false });
    }
  }
  render() {
    const loader = this.state.codeRendering ? <Loader /> : null;
    return (
      <span>
        {loader}
        <SyntaxWrapper {...this.props} />
      </span>
    );
  }
}
```

**Comment by bmathews** [comment]
For a big file, you'll be rendering thousands of elements. The only way to
solve that is to lazy render elements based on viewport size and scrollTop,
which isn't really possible unless we're able to wrap each line in an
element.

**Comment by gala132** [comment]
All right.
So this is not really possible with the library "as is", this now basically works for small lines of code. Are there plans to "make it work" with more lines like the example I described?
Otherwise I will have to move to server side rendering which I wanted to not have in the first place.

**Comment by gala132** [comment]
Well, I probably won't need that much though, but was just considering a case of that.
But thank you for your work, it works flawlessly. Keep up the good work. :+1:

**Comment by conorhastings** [comment]
@gala132 created #53 to explore potential lazy render - the newest release which allows line wrapping should allow us to explore
