### ISSUE TITLE
lazily render elements not on screen

### ISSUE THREAD

**Issue by conorhastings** [conorhastings/react-syntax-highlighter#53]

**Comment by bmathews** [comment]
Most lazy/virtualized rendering components/hocs require either

1) A flat list of elements for it to lazy render
2) A `rowRenderer` method for you to return a single row, as well as the number of items and rowHeight

It might make sense expose a `renderer` prop (or something like it() that allows custom rendering of all the row elements. In the case of react-virtualized, it could look something like this:

```jsx
const rowRenderer = (rows, {key, index, style}) => {
  return <div key={key} style={style}>{rows[index]}</div>
}

const renderer = rows => {
  return <ReactVirtualizedList rowCount={rows.length} rowHeight={25} rowRenderer={rowRenderer.bind(null, rows)} />;
}

const codeSnippet = `function () { \n alert(); };`

return (
  <SyntaxHighlighter renderer={renderer} language="javascript">
     {codeSnippet}
  </SyntaxHighlighter>
);
```

**Comment by conorhastings** [comment]
@bmathews I like that, that way naive render everything default renderer can be built in and users could use react-virtualized or whatever they like to handle the rest 

could also release a react virtualized plugin but not needed as part of core

**Comment by bvaughn** [comment]
I'm a fan of releasing a separate plugin/adapter. I've done this with things like react-select to tie it into react-virtualized and js-search and it's worked out nicely.

**Comment by conorhastings** [comment]
now possible with custom renderers and https://github.com/conorhastings/react-syntax-highlighter-virtualized-renderer 🆒 😎 , thanks for the input everyone!
