### ISSUE TITLE
Not able to require the styles?

### ISSUE THREAD

**Issue by hemanth** [conorhastings/react-syntax-highlighter#6]
Getting a `Uncaught Error: Cannot find module './styles/docco'` for 

```js
import SyntaxHighlighter from 'react-syntax-highlighter';
const Component = () => {
  const codeString = '(num) => num + 1';
  return <SyntaxHighlighter language='javascript' stylesheet='docco'>{codeString}</SyntaxHighlighter>;  
}
```

**Comment by conorhastings** [comment]
Hey @hemanth , what are you currently using to bundle your code? Currently this module requires webpack because of the use of dynamic require statements , but i'm exploring ways to get away from that.

**Comment by hemanth** [comment]
@conorhastings Just noticed, I am using browserify.
