### ISSUE TITLE
How to provide custom classes

### ISSUE THREAD

**Issue by vaibhavswarnkar** [conorhastings/react-syntax-highlighter#61]
How do I customize the styling of code string I'm providing to the Highlighter.
Example I've a string JSON available and I want the color of attributes to be different than shipped with themes.

**Comment by conorhastings** [comment]
@vaibhavswarnkar you can provide your own theme, you would just need to pass in something fulfilling these properties -- https://github.com/conorhastings/react-syntax-highlighter/blob/master/src/styles/agate.js
