### ISSUE TITLE
React.createElement: type should not be null, undefined, boolean, or number

### ISSUE THREAD

**Issue by marcelpanse** [conorhastings/react-syntax-highlighter#7]
I'm using React 15.0.0

Full stacktrace:

```warning.js:44 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `HtmlTab`.warning @ warning.js:44ReactElementValidator.createElement @ ReactElementValidator.js:221HtmlTab_render @ HtmlTab.jsx:48(anonymous function) @ makeAssimilatePrototype.js:15ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:679ReactCompositeComponentMixin._renderValidatedComponent @ ReactCompositeComponent.js:699ReactCompositeComponent__renderValidatedComponent @ ReactPerf.js:66ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:284ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39mountComponentIntoNode @ ReactMount.js:103Mixin.perform @ Transaction.js:136batchedMountComponentIntoNode @ ReactMount.js:124Mixin.perform @ Transaction.js:136ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:97ReactMount._renderNewRootComponent @ ReactMount.js:277ReactMount__renderNewRootComponent @ ReactPerf.js:66ReactMount._renderSubtreeIntoContainer @ ReactMount.js:354ReactMount.render @ ReactMount.js:374React_render @ ReactPerf.js:66(anonymous function) @ mainApp.jsx:34(anonymous function) @ mainApp.jsx:75(anonymous function) @ mainApp.jsx:76(anonymous function) @ main.jsundefined:1264__webpack_require__ @ main.jsundefined:545fn @ main.jsundefined:76(anonymous function) @ multi_main:3(anonymous function) @ main.jsundefined:578__webpack_require__ @ main.jsundefined:545(anonymous function) @ main.jsundefined:568(anonymous function) @ main.jsundefined:571
invariant.js:38``` 

```Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `HtmlTab`.invariant @ invariant.js:38instantiateReactComponent @ instantiateReactComponent.js:66instantiateChild @ ReactChildReconciler.js:28traverseAllChildrenImpl @ traverseAllChildren.js:98traverseAllChildren @ traverseAllChildren.js:186ReactChildReconciler.instantiateChildren @ ReactChildReconciler.js:51ReactMultiChild.Mixin._reconcilerInstantiateChildren @ ReactMultiChild.js:159ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:196ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:617ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:465ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39mountComponentIntoNode @ ReactMount.js:103Mixin.perform @ Transaction.js:136batchedMountComponentIntoNode @ ReactMount.js:124Mixin.perform @ Transaction.js:136ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:97ReactMount._renderNewRootComponent @ ReactMount.js:277ReactMount__renderNewRootComponent @ ReactPerf.js:66ReactMount._renderSubtreeIntoContainer @ ReactMount.js:354ReactMount.render @ ReactMount.js:374React_render @ ReactPerf.js:66(anonymous function) @ mainApp.jsx:34(anonymous function) @ mainApp.jsx:75(anonymous function) @ mainApp.jsx:76(anonymous function) @ main.jsundefined:1264__webpack_require__ @ main.jsundefined:545fn @ main.jsundefined:76(anonymous function) @ multi_main:3(anonymous function) @ main.jsundefined:578__webpack_require__ @ main.jsundefined:545(anonymous function) @ main.jsundefined:568(anonymous function) @ main.jsundefined:571
8ReactDOMComponentTree.js:105``` 

```Uncaught TypeError: Cannot read property '__reactInternalInstance$0rtr6rqckkdzhlrxlg3vt8d7vi' of null```

**Comment by conorhastings** [comment]
@marcelpanse I'm unable to reproduce the error, is there anyway you can share code that reproduces?

**Comment by marcelpanse** [comment]
Not at the moment, I went back to react 14 because I don't have much time for it now, will try another time.

**Comment by conorhastings** [comment]
sounds good, please let me know if you ever have that code.
