### ISSUE TITLE
[Question] line style does not work as I expected

### ISSUE THREAD

**Issue by zjkyz8** [conorhastings/react-syntax-highlighter#70]
Sorry to create an issue here.
Now I am using this component to create a git diff view component. I found if some of the codes are too long to overflow the width of highlighter, the background of line will be cut.  You can get more info from below screenshot.
![image](https://cloud.githubusercontent.com/assets/1856389/25688076/82a89b58-30ae-11e7-8496-3935d1dca218.png)

If this issue is not a good issue, please feel free to close it. :)

**Comment by conorhastings** [comment]
@zjkyz8 I'm not sure i understand, did you manually edit the size of the pre tag on that page? could that have something to do with it?

**Comment by zjkyz8** [comment]
no, i do not change the size of pre tag, I just declare a div with a width limitation,  and put highlight in that div. my jsx like below:
`<div>
	<div style={{width: '50%', overflow: 'auto'}}>
        	<SyntaxHighlighter language={language} wrapLines showLineNumbers='true' 
			lineStyle={lineNumber => this.constructor.generateLineStyle(oldCodes, lineNumber, 			'deleted', '#ffecec')} 
			style={docco} 
			renderer={(args) => this.lineRenderer(Object.assign(args, {codes: oldCodes}))} lineNumberRenderer={(args) => this.constructor.renderLineNumber(Object.assign(args, {codes: oldCodes}))}
			lineNumberContainerStyle={this.constructor.lineNumberContainerStyle}
		>{oldCodes}</SyntaxHighlighter>
	</div>
        <div style={{width: '50%', overflow: 'auto'}}>
		<SyntaxHighlighter language={language} wrapLines showLineNumbers="true" 
			lineStyle={lineNumber => this.constructor.generateLineStyle(newCodes, lineNumber, 'added', '#dbffdb')} 
			style={docco}  
			renderer={(args) => this.lineRenderer(Object.assign(args, {codes: newCodes}))} lineNumberRenderer={(args) => this.constructor.renderLineNumber(Object.assign(args, {codes: newCodes}))}
			lineNumberContainerStyle={this.constructor.lineNumberContainerStyle}
		>{newCodes}</SyntaxHighlighter>    
	</div>
</Block>`

So you can see the outer div has the width. like the previous screenshot.

**Comment by conorhastings** [comment]
thanks for providing the code, i'll take a look tonight

**Comment by zjkyz8** [comment]
Sorry to reply so late, I tried your solution, the problem is still there. I guess the root cause is span limitation, but I can not get a way to verify my guess.

**Comment by conorhastings** [comment]
@zjkyz8 thanks for trying that, I'll have time in  the next couple days to take a look and will update here

**Comment by conorhastings** [comment]
@zjkyz8 can you show me wht this function looks like -- generateLineStyle

**Comment by zjkyz8** [comment]
Yes, of course.
basically speaking, this method decide whether we need add a diff style on a line.
you can access this link http://conor.rodeo/react-syntax-highlighter/demo/diff.html.
I do the same as demo in link.

**Comment by conorhastings** [comment]
@zjkyz8 there are likely other ways to style that will support your use case but i'm not sure anything needs to be changed in the module to do it. i'm not sure of a solution but if you find one that requires change to the highlighter I woud definitely accept a pr, thanks! sorry i couldn't be of more help
