### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by ernieturner** [conorhastings/react-syntax-highlighter#71]
This project currently doesn't have a LICENSE file so it's unknown what can be done with this code. Would it be possible to add a license to this so it can safely be used by consuming projects?

https://choosealicense.com/

**Comment by conorhastings** [comment]
added here -- https://github.com/conorhastings/react-syntax-highlighter/commit/2a21fda14f1a1c8ec5bd5a61c1b5aa7ef070b35f

and published `v5.5.1` so there is a version on npm with a license

**Comment by ernieturner** [comment]
Thank you!
