### ISSUE TITLE
The whole line is commented when using wrapLines

### ISSUE THREAD

**Issue by roeyhorw** [conorhastings/react-syntax-highlighter#74]
![issue](https://cloud.githubusercontent.com/assets/4451461/26193314/9d8cc79a-3bbd-11e7-8a76-07b635051834.png)

and thanks for the great project

**Comment by conorhastings** [comment]
@roeyhorw can you post your code if possible?

**Comment by roeyhorw** [comment]
`
    render() {

        const code = "int a;\ndo_something(a);//commnet"
        return (
                <SyntaxHighlighter language='cpp'
                    style={arta}
                    wrapLines={true}
                >
                {code}
                </SyntaxHighlighter>
        )
    }
`

**Comment by conorhastings** [comment]
thanks for the pr, published as `v5.6.1`
