### ISSUE TITLE
lineStyles attached to line children and missing line numbers

### ISSUE THREAD

**Issue by KirioXX** [conorhastings/react-syntax-highlighter#76]
![screen shot 2017-05-25 at 14 17 28](https://cloud.githubusercontent.com/assets/11646702/26451703/10a567cc-4155-11e7-96a7-e87a7c83769c.png)

I have as you can see, in the picture, a problem with the lineStyles.
At first, they are attached to the child spans, with this I have the problem that I get unexpected line breaks. Probably are this line breaks also the problem why the line numbers break up on line 40 (I used the line numbers just for be debugging purposes).
I load the code via redux-sagas and bind them then like this:

```
<SyntaxHighlighter
      language='java'
      wrapLines
      lineStyle={(lineNumber: number) => {
         const style = { display: '', backgroundColor: '' };
         if (this.state.fileCoverage.COVERED.includes(lineNumber)) {
              style.display = 'block';
              style.backgroundColor = '#A9DBB8';
         } else if (this.state.fileCoverage.COVERED_NEW.includes(lineNumber)) {
             style.display = 'block';
             style.backgroundColor = '#EDE4AF';
         } else if (this.state.fileCoverage.UNCOVERED.includes(lineNumber)) {
             style.display = 'block';
             style.backgroundColor = '#BA2D0B';
         }
         return style;
      }}
      showLineNumbers
    >
     {this.props.codeFile}
</SyntaxHighlighter>
```

Thanks

**Comment by conorhastings** [comment]
@KirioXX thanks for the issue, could you by any chance post the version of the module you're using and if possible the contents of this.props.codeFile

Thanks!

**Comment by KirioXX** [comment]
Thanks for the response. Yes the version of react-syntax-highlighter is 5.6.1, with the typings on version 0.0.2 and the content of this.props.codeFile is this:
```
"package com.javatest;\n\npublic class BubbleSort {\n  /**\n   * Applies bubble sort to an array and returns whether the array was sorted correctly.\n   */\n  public boolean checkSort(int[] a) {\n    sort(a);\n\n    for (int i = 0; i < a.length - 1; i++) {\n      if (a[i] > a[i + 1]) {\n        return false;\n      }\n    }\n\n    return true;\n  }\n\n  /**\n   * Bubble sort an array, mutating the array (contains a bug).\n   */\n  public void sort(int [] a) {\n    int j;\n    boolean flag = true;\n    int temp;..."
```

**Comment by conorhastings** [comment]
@KirioXX thanks, i'm at work now, i'lll look into this tonight

**Comment by conorhastings** [comment]
@KirioXX it appears this was broken in 5.6.1, apologies, it should work correctly if you use 5.6.0 and i'm going to look into what broke it today. Sorry again.

**Comment by conorhastings** [comment]
I'll utilize a version of your code to make a test for future versions, thanks 👍

**Comment by conorhastings** [comment]
should be fixed now, with test added from your example

`v5.6.2` for fixed version, thanks again for the report

**Comment by KirioXX** [comment]
@conorhastings Thank you very much, it works perfect 👍

**Comment by conorhastings** [comment]
@KirioXX no problem, thanks again for the great report

Sorry it took so long to get to
