### ISSUE TITLE
Light Build and Webpack 2 still load all highlight.js languages

### ISSUE THREAD

**Issue by enzolutions** [conorhastings/react-syntax-highlighter#78]
Hi folks.

Thank you for this awesome package.

Today I was to raise an issue related wit bundle size.

I am trying to use the light build as you can see in the following code

```js
import SyntaxHighlighter, { registerLanguage } from "react-syntax-highlighter/dist/light"

import foundation from 'react-syntax-highlighter/dist/styles/foundation';

['javascript', 'php', 'xml', 'bash', 'markdown', 'json', 'yaml'].forEach((langName) => {
    const langModule = require(`react-syntax-highlighter/dist/languages/${langName}`);
    registerLanguage(langName, langModule);
});
```

But when you use **Webpack 2** to create a package, the [tree shaking](https://webpack.js.org/guides/tree-shaking/) logic doesn't work as you can see in the following image.
<img width="543" alt="all-languajes-includes" src="https://cloud.githubusercontent.com/assets/907914/26706639/5d941c58-4782-11e7-955a-d6194cef1dc7.png">

I asked in webpack forums, and people mentioned that maybe internally maybe all languages are included.

I tried also trying to exclude with the same result

```js
new webpack.IgnorePlugin(/^\.\/lib\/languages$/, /highlight\.js/),
```

I would really appreacite any recommendation.

**Comment by bmathews** [comment]
I believe when you do a dynamic require like that, webpack can't determine what to include so it just includes the whole folder of the static string part of your require. Try switching to just 7 static imports and see if that solves the problem.

**Comment by conorhastings** [comment]
@bmathews yup believe that's correct

**Comment by enzolutions** [comment]
Hi @bmathews and @conorhastings 

I just update my code as you suggested.

```js
import SyntaxHighlighter, { registerLanguage } from "react-syntax-highlighter/dist/light"

import foundation from 'react-syntax-highlighter/dist/styles/foundation';

const javascript = require('react-syntax-highlighter/dist/languages/javascript');
const php = require('react-syntax-highlighter/dist/languages/php');
const xml = require('react-syntax-highlighter/dist/languages/xml');
const bash = require('react-syntax-highlighter/dist/languages/bash');
const markdown = require('react-syntax-highlighter/dist/languages/markdown');
const json = require('react-syntax-highlighter/dist/languages/json');
const yaml = require('react-syntax-highlighter/dist/languages/yaml');

registerLanguage('javascript', javascript);
registerLanguage('php', php);
registerLanguage('xml', xml);
registerLanguage('bash', bash);
registerLanguage('markdown', markdown);
registerLanguage('json', json);
registerLanguage('yaml', yaml);
```

Also I did an update in my webpack with the following entries

```js
    var entries = {
        "syntax-highlighter": ['react-syntax-highlighter/dist/light', 'highlight.js'],
        "syntax-highlighter-languages": ['react-syntax-highlighter/dist/languages/javascript',
            'react-syntax-highlighter/dist/languages/php', 'react-syntax-highlighter/dist/languages/xml',
            'react-syntax-highlighter/dist/languages/bash', 'react-syntax-highlighter/dist/languages/markdown',
            'react-syntax-highlighter/dist/languages/json', 'react-syntax-highlighter/dist/languages/yaml'
        ],
        "syntax-highlighter-foundation": ['react-syntax-highlighter/dist/styles/foundation']
    };
```
 
Also, I am using  [CommonsChunkPlugin](https://webpack.js.org/plugins/commons-chunk-plugin) to create a separate file to be loaded in browsers
```js
        new webpack.optimize.CommonsChunkPlugin({
            names: ["syntax-highlighter", "syntax-highlighter-languages", "syntax-highlighter-foundation"],
            minChunks: Infinity
        })
       
```

However, the output is the same with all languages inside.

<img width="524" alt="screen shot 2017-06-02 at 1 16 38 pm" src="https://cloud.githubusercontent.com/assets/907914/26709549/cb780b62-4796-11e7-95a9-f2f583eb39bc.png">

Thanks in advance

**Comment by bmathews** [comment]
Why are you loading in all of highlight.js?

`"syntax-highlighter": ['react-syntax-highlighter/dist/light', 'highlight.js'],` ?

**Comment by bmathews** [comment]
That'll give you everything required in: https://unpkg.com/highlight.js@9.12.0

**Comment by enzolutions** [comment]
Hi, 

I removed that, but now I got an error in execution.

syntax-highlighter.js:190 Uncaught TypeError: syntax is not a function

<img width="421" alt="screen shot 2017-06-06 at 11 04 29 am" src="https://cloud.githubusercontent.com/assets/907914/26809419/f3879460-4aa7-11e7-8599-5c27d8eede95.png">

**Comment by zsherman** [comment]
@enzolutions got this too, if you're trying to use a language in the new version of highlight.js that isn't in `react-syntax-highlighter/dist/languages` you'll see this error. Really there should be a simple way to keep the two packages up to date.

**Comment by conorhastings** [comment]
@enzosolutions @zsherman are you still seeing this on the latest version?

**Comment by zsherman** [comment]
looks good, thanks @conorhastings

**Comment by enzolutions** [comment]
I am not able to test in next two days, but I am wondering if @zsherman could share how he tested the latest version.

Kind regards,

**Comment by SeanSilke** [comment]
@enzolutions There is update of the package on npm the version is v5.6.3.
 You can use` npm update react-syntax-highlighter`.

**Comment by stereokai** [comment]
How do you get this awesome visual breakdown of your dependency tree?

**Comment by Kobzol** [comment]
@stereokai webpack-bundle-analyzer

**Comment by stereokai** [comment]
Cheers!
