### ISSUE TITLE
Update README on npm

### ISSUE THREAD

**Issue by simonlovesyou** [conorhastings/react-syntax-highlighter#8]
The README on npm doesn't correctly show how to retrieve the script styles, it says

```
import { docco } from 'react-syntax-highlighter/styles';
```
while it should be

```
import { docco } from 'react-syntax-highlighter/dist/styles';
```

It should be a quick fix :)

**Comment by conorhastings** [comment]
yup, it's fixed on master, just needs to be pushed to npm, will do today, thanks!

**Comment by conorhastings** [comment]
@simonlovesyou updared on npm, thanks for the issue!
