### ISSUE TITLE
Duplicate package highlight.js

### ISSUE THREAD

**Issue by SeanSilke** [conorhastings/react-syntax-highlighter#80]
Hello @conorhastings.

There is duplication of highlight.js in dist build of your lib.

Your lib require[ highlight.js": ~9.8.0](https://github.com/conorhastings/react-syntax-highlighter/blob/master/package.json#L8) and [lowlight": ^1.5.0](https://github.com/conorhastings/react-syntax-highlighter/blob/master/package.json#L8)
The lowlight that is end up in use is "1.9.0" i.e the latest.
And that latest lowlight is using [highlight.js": "~9.12.0](https://github.com/wooorm/lowlight/blob/master/package.json#L28)

So webpack include both version.

As i can see there are several possible solutions.

- go from "Caret Ranges" to "Tilde Ranges"   for  lowlight and fixate version more tight.
- remove highlight.js from dependencies and use that of lowlight

**Comment by conorhastings** [comment]
@SeanSilke thanks for the issue, I'll try to get to it this weekend, if you have ideas of an ideal solution though feel free to submit a pr

**Comment by conorhastings** [comment]
@SeanSilke published `v5.6.3` which should allviate will try to keep up to date in the future / set up greenkeeper

**Comment by SeanSilke** [comment]
@conorhastings grate thank! 

 Sorry for long response. Does't make PR because was not sure why you chose to use ~version for packets instead of ^version.

One thing more: In current form you will need manually manage upgrading of version.

Maybe it is good idea to use peerdependencies for highlight.js? Setup the range of version and npm will emit warnings if range is not met.

**Comment by conorhastings** [comment]
@SeanSilke going to update highlight.js to be a dev dependency since currently only used to build assets and not neccearily for any actual use of app, thanks for the idea!
