### ISSUE TITLE
Unknown language breaks highlighter

### ISSUE THREAD

**Issue by will-hart** [conorhastings/react-syntax-highlighter#82]
I'm using `react-syntax-highlighter` to highlight markdown user input. The user can manually type in the language that is being used in fenced code block style, e.g.

```markdown
```js
```

The problem is that when the user is typing in the language, i.e. they hit `j` in the example above, `react-syntax-highlighter` tries to render in the language `j`, which means it throws an "unknown language" error and stops rendering correctly:

```
Uncaught Error: Unknown language: `j` is not registered
    at coreHighlight (core.js:159)
```

Is there a way to either ignore these errors (and just revert to autodetection if the language is not loaded) or to find out whether a given language is registered prior to setting it as a prop?

**Comment by conorhastings** [comment]
@will-hart nice catch, fixed in `v5.7.0` by falling back to highlightAuto if language is not registered
