### ISSUE TITLE
Wraps automatically

### ISSUE THREAD

**Issue by o02112** [conorhastings/react-syntax-highlighter#86]

**Comment by conorhastings** [comment]
@o02112 can you describe more in detail?

**Comment by o02112** [comment]
If a code line is longer than the container's width. It might Wraps automatically

**Comment by FatihBAKIR** [comment]
Not only it breaks the code, it also creates a new line number for the remaining part of the line

**Comment by afraser** [comment]
Sounds outside the scope of this project. What you're describing could be emulated with css or fully handled by a code formatter like [prettier](https://github.com/prettier/prettier)

**Comment by conorhastings** [comment]
agreed with @afraser but please let me know if being interpreted wrong

**Comment by erykpiast** [comment]
@afraser, @conorhastings  could you provide an example of how to wrap lines with CSS, including line numbers?
