### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by sslotsky** [conorhastings/react-syntax-highlighter#9]
Highlight.js claims to support JSX, but you can tell by the screenshots below that JSX entered into `react-syntax-highlighter` does not get the correct coloring applied to the tags. Is this an issue with this library, or with Highlight.js itself?

![screenshot from 2016-05-05 22-13-43](https://cloud.githubusercontent.com/assets/374078/15063310/b5fd253c-130e-11e6-94ec-896996f93d80.png)

![screenshot from 2016-05-05 22-15-42](https://cloud.githubusercontent.com/assets/374078/15063331/ed92fbf2-130e-11e6-854d-d006eb4954eb.png)

**Comment by sslotsky** [comment]
It looks like they just added support for this in February. Any chance of pulling in the updates?

https://highlightjs.org/#news-92

**Comment by conorhastings** [comment]
Thanks for the issue, I'll try to take a look at this today.

**Comment by conorhastings** [comment]
seems like the support isn't quite there, https://github.com/isagalaev/highlight.js/issues/931#issuecomment-214824138 . I'll leave this open to track updates on the highlightjs side.

**Comment by sslotsky** [comment]
I see, thanks for looking into that. If those grammars aren't too messy to define, perhaps I'll take a swing.

**Comment by sslotsky** [comment]
Not _awful_ I guess. Certainly lacking in elegance compared to ocaml/f# lexing/parsing tools.

https://github.com/isagalaev/highlight.js/blob/master/src/languages/javascript.js

https://github.com/isagalaev/highlight.js/blob/master/src/languages/xml.js

**Comment by zekedroid** [comment]
Any updates on this?

**Comment by conorhastings** [comment]
@zekedroid currently still just waiting for highlight.js support, i don't currently have the bandwidth to do it myself

**Comment by joaomilho** [comment]
+1

**Comment by bmathews** [comment]
Seems to be supported now.

**Comment by conorhastings** [comment]
@bmathews cool, i'll try to take a look this weekend

**Comment by bmathews** [comment]
Eh, nevermind, it's still not much better than the last screenshot despite some recent activity around it.

**Comment by lukaswelinder** [comment]
@conorhastings For some reason JSX syntax highlighting is still not working. It appears alright on the demo though; any ideas?

**Comment by lopis** [comment]
Not a solution, but using HTML syntax works well for the HTML part of JSX.

**Comment by wooorm** [comment]
[`refractor`](https://github.com/wooorm/refractor) may help! 😉

**Comment by deniztetik** [comment]
Had the same problem. Just used [`react-codemirror`](https://github.com/JedWatson/react-codemirror) instead for JSX. It doesn't seem to have the same issue.

**Comment by conorhastings** [comment]
@maxmcd nice

definitely interested in pulling this in although probably with an option to use with highlight.js or refractor (will need a non confusing way of determining language availability and styles though so requires some thinking) 

Ill try to take a look at your code soon

**Comment by maxmcd** [comment]
@conorhastings Awesome. Yes, agreed, would be particularly interested in your thoughts on the cross-parser language/style issue. Couldn't think of an elegant way to combine those two.

**Comment by conorhastings** [comment]
@maxmcd my initial thought is allow passing in an astGenerator (lowlight, or refractor, default to lowlight). Then use dev mode warnings if style or language not available for that particular module. 

still don't love that though, so will give more thought

**Comment by maxmcd** [comment]
@conorhastings ah, and then less about building available styles and more about dynamically passing values. That's not too bad

**Comment by conorhastings** [comment]
@maxmcd basically made a pr from your branch and will branch off and work through some ideas, i'll ping you for a look some time soon

**Comment by conorhastings** [comment]
now supported when imported 'react-syntax-highlighter/prism' and jsx as language. this is very new so please report any bugs you see when using with prism/refractor

thanks for the extreme patience!

**Comment by esr360** [comment]
```jsx
import SyntaxHighlighter from 'react-syntax-highlighter/prism';
import { xonokai } from 'react-syntax-highlighter/styles/prism';

<SyntaxHighlighter language='jsx' style={xonokai}>{
     '<Alert>This is an alert bar</Alert>'
}</SyntaxHighlighter>
```

Seems to work great 🎉

**Comment by Hydrock** [comment]
I trying **language='javascript|html'**
Its work for me - sometimes

**Comment by GAUTAMRAJU15** [comment]
> ```js-jsx
> import SyntaxHighlighter from 'react-syntax-highlighter/prism';
> import { xonokai } from 'react-syntax-highlighter/styles/prism';
> 
> <SyntaxHighlighter language='jsx' style={xonokai}>{
>      '<Alert>This is an alert bar</Alert>'
> }</SyntaxHighlighter>
> ```
> 
> Seems to work great 🎉

This won't work now, the style path is invalid
