### ISSUE TITLE
Editable Code

### ISSUE THREAD

**Issue by tomtwttr** [conorhastings/react-syntax-highlighter#92]
I was able to get static code up and running with react-syntax-highlighter quickly but I'm still struggling with an editable version. Any chance one of you guys/gals have the bandwidth to add some sort of simple onChange props support that works with line numbers?

I was hoping I'd be able to use SyntaxHighlighter like this...
```
export default class MyCodeComponent extends React.PureComponent {

	constructor(props) {
		this.state = {code: this.props.initialCode};
	}

	onCodeChange(codeString) {
		this.setState({code: codeString});
	}

	render() {
		return (
		<SyntaxHighlighter language='javascript' showLineNumbers={true} spellCheck={false} onChange={this.onCodeChange}>
		  {this.state.code}
		</SyntaxHighlighter>
		);
	}
}
```

**Comment by conorhastings** [comment]
content editable in react is difficult, it should be theoretically possible to implement on top of this library (maybe draftjs would provide good examples) but I don't think it will be implemented as part of this library

**Comment by hsluoyz** [comment]
This one can be solved.

**Comment by hsluoyz** [comment]
Any update?

**Comment by haydenbleasel** [comment]
React Syntax Highlighter is, as it's name suggests, a syntax highlighter and not a code editor. If you want full code editing, I'd check out something like [Monaco](https://github.com/microsoft/monaco-editor) or [Ace](https://ace.c9.io/).

However, if you're keen to stick with this package, you can cheat an editable state. I wrote up a post on [how to achieve this](https://www.beskar.co/blog/making-react-syntax-highlighter-editable).

**Comment by BhandarkarPawan** [comment]
@haydenbleasel the link seems broken
