### ISSUE TITLE
Silence warnings in React 16

### ISSUE THREAD

**Issue by markbrown4** [conorhastings/react-syntax-highlighter#93]
There's warnings running the prism highlighter in `react-dom@16.0.0`

```
import SyntaxHighlighter from 'react-syntax-highlighter/prism'

<SyntaxHighlighter language='json'>
  {JSON.stringify(content, null, 2)}
</SyntaxHighlighter>
```

> Check the render method of `SyntaxHighlighter`.
> Warning: Unsupported vendor-prefixed style property mozTabSize. Did you mean MozTabSize?
> Warning: Unsupported vendor-prefixed style property oTabSize. Did you mean OTabSize?
> Warning: Unsupported vendor-prefixed style property webkitHyphens. Did you mean WebkitHyphens?
> Warning: Unsupported vendor-prefixed style property mozHyphens. Did you mean MozHyphens?

**Comment by conorhastings** [comment]
@markbrown4 published `v6.0.4` which i believe will fix your issue, please let me know!

**Comment by markbrown4** [comment]
Thanks! I can't seem to download `v6.0.4` though

> 6.0.3 is the latest of 57 releases

**Comment by conorhastings** [comment]
@markbrown4 sorry forgot to publish, can you try now
