### ISSUE TITLE
Prism-themes dependency

### ISSUE THREAD

**Issue by GeeWizWow** [conorhastings/react-syntax-highlighter#95]
Hey

We're having some issues with the prism-themes dependency being listed as a repo url on our build agents that don't have git installed.

Would it be possible to either put it into dev-dependencies (it doesn't look like it's used at all a part from pre-publish) or use the npm package ?

https://www.npmjs.com/package/prism-themes

Happy to submit a pr for one or the other.

Cheers, Finn

**Comment by conorhastings** [comment]
published as `v6.1.1` , thanks!

**Comment by GeeWizWow** [comment]
Thanks a million, cheers
