### ISSUE TITLE
Need for hardcoded container styles?

### ISSUE THREAD

**Issue by danawoodman** [conorhastings/react-syntax-highlighter#97]
Is there a reason that react-syntax-highlighter includes inline styles directly on the wrapper `<pre>` tag?

This makes changing the default styling next to impossible, especially since they're style tags on the element and there is no way to override them from what I can tell. A use case I have come across is using this plugin to render inline syntax highlighting. 

It appears this is defined in the actual style files, [like here](https://github.com/conorhastings/react-syntax-highlighter/blob/64f3c44cc5fc20abff31348f6b2a0090a506cf60/src/styles/hljs/ascetic.js#L2) for example. Specifically I am talking about the padding/display settings since these mess up inline styling.

Is there a way to remove these, plans to remove these from the styles or a plans for a way to remove them? Maybe a `className` could be passed to the wrapper by the parent component?

Thanks!

**Comment by conorhastings** [comment]
it should be possible to remove. you can essentaily do this
```js
/* 1 */
import docco from ".react-syntax-highlighter/styles/doco';
const highlightStyle = Object.assign({}, docco);
highlightStyle.hljs = {};
<SyntaxHighlighter style={highlightStyle}>console.log('hi')<SyntaxHighlighter>
```

**Comment by conorhastings** [comment]
you can also pass in a customStyle attribute if you which to also add styles to the pre tag

**Comment by danawoodman** [comment]
@conorhastings thanks for the tips, I will try these out!
