### ISSUE TITLE
JSX Highlighting issue 

### ISSUE THREAD

**Issue by aarondack** [conorhastings/react-syntax-highlighter#98]
Hi there, 

I seem to have run into an issue where jsx highlighting is not happening. This is testing react-syntax-highlighter in CRA with just this lib installed.

```javascript
import React, { Component } from "react";
import SyntaxHighlighter from "react-syntax-highlighter/prism";
import { dark } from "react-syntax-highlighter/styles/prism";

class App extends Component {
  render() {
    const testString = `
    import React from "react";
    import uniquePropHOC from "./lib/unique-prop-hoc";

    class Expire extends React.Component {
      constructor(props) {
          super(props);
          this.state = { component: props.children }
      }
      componentDidMount() {
          setTimeout(() => {
              this.setState({
                  component: null
              });
          }, this.props.time || this.props.seconds * 1000);
      }
      render() {
          return this.state.component;
      }
  }

  export default uniquePropHOC(["time", "seconds"])(Expire);
`;
    return (
      <SyntaxHighlighter langugage="jsx" style={dark}>
        {testString}
      </SyntaxHighlighter>
    );
  }
}

export default App;

```

![image](https://user-images.githubusercontent.com/8890348/34499557-a048b4c8-efd4-11e7-9d40-93123865d6b0.png)

When I use `hljs` I get colored versions but obviously not the correct jsx highlighting. Any ideas?

**Comment by conorhastings** [comment]
@aarondack at work now, but will try to look into this tonight, thanks for the report

**Comment by conorhastings** [comment]
@aarondack looks like you just hava a typo, langugage="jsx" should be language="jsx" , i tested myself, but please let me know if it's not working for you still

**Comment by aarondack** [comment]
@conorhastings Derp, sorry for the bother!
